(function(){RIGHTMOVE.namespace("RIGHTMOVE.PROPERTYDETAILS").imageGallery=function(){function p(b){k(b)||setTimeout(function(){$(a.mainImageContainer).attr("src",a.loadingMainImageSrc)},0)}function k(a){if(c&&!c.getFailureImageBySrc(a)){a:{for(var m=c.loadedImages,e=0;e<m.length;++e)if(m[e]&&m[e].src==a){a=!0;break a}a=!1}return a}return!1}var f=0,d=0,q=0,c,a={images:[],mainImageContainer:"#mainphoto",nextImageSelector:".nextphotolink",prevImageSelector:".prevphotolink",imageThumbnailSelector:".thumbnailimage",
currentSelectedImageIndex:0,slideshowToggle:"#slideshow",thumbnailCarousel:void 0,imageThumbnailIdPrefix:"thumbnail-",captionContainer:"#captiontext",fullscreenLink:"#fullscreengallery a",imageIndex:"#photoindex",selectedThumbnailClass:"selected",slideshowIntervalMillis:2E3,numberOfImagesToPreloadBeforeCurrent:1,numberOfImagesToPreloadAfterCurrent:4,enableLeftAndRightKeyPressNavigation:!0,loadingMainImageSrc:void 0,failureMainImageSrc:void 0},u=function(){$(a.mainImageContainer).error(function(){r()})},
v=function(b,c){$(a.captionContainer).html(b);$(a.fullscreenLink).attr("href",function(a,b){return b.replace(/photoIndex=\d+/,"photoIndex\x3d"+c)});$(a.imageIndex).html(c+1);$(a.mainImageContainer).attr("alt",b)},h=function(b,m,e){d!=b&&($(a.imageThumbnailSelector).removeClass(a.selectedThumbnailClass),d=b,e?$(a.mainImageContainer).fadeTo(200,0.2,function(){d==b&&s(a.images[b].masterUrl);$(a.mainImageContainer).fadeTo(200,1)}):s(a.images[b].masterUrl),v(a.images[b].caption,b),$("#thumbnail-"+b).parent().addClass(a.selectedThumbnailClass),
a.thumbnailCarousel&&a.thumbnailCarousel.selectedImageUpdated(b,m),c&&c.updateCurrentIndex(b))},w=function(b,c){a.loadingMainImageSrc?(p(b),setTimeout(function(){c(b)},100)):c(b)},r=function(){a.failureMainImageSrc&&$(a.mainImageContainer).attr("src",a.failureMainImageSrc)},s=function(b){w(b,function(b){c&&c.isImageSrcFailure(b)&&a.failureMainImageSrc?r():$(a.mainImageContainer).attr("src",b)})},l=function(a){return d+a>f?d+a-f-1:0>d+a?d+a+f+1:d+a},t=function(){$(a.slideshowToggle).addClass("active");
$(a.slideshowToggle).html("Stop slideshow");q=window.setInterval(function(){h(l(1),!0,!0)},a.slideshowIntervalMillis)},n=function(){window.clearInterval(q);$(a.slideshowToggle).removeClass("active");$(a.slideshowToggle).html("Start slideshow")},x=function(){$(document).on("click",a.nextImageSelector,function(){n();1<a.images.length&&h(l(1),!0,!1);return!1});$(document).on("click",a.prevImageSelector,function(){n();1<a.images.length&&h(l(-1),!0,!1);return!1});a.enableLeftAndRightKeyPressNavigation&&
$(document).keydown(function(b){1<a.images.length&&(37==b.keyCode||39==b.keyCode)&&(n(),37==b.keyCode?h(l(-1),!0,!1):h(l(1),!0,!1))});$(document).on("click",a.imageThumbnailSelector,function(b){b.preventDefault();n();h(parseInt($(this).find("a").attr("id").replace(a.imageThumbnailIdPrefix,""),10),!1,!1);return!1});$(document).on("click",a.slideshowToggle,function(){1<a.images.length&&($(a.slideshowToggle).is(".active")?n():t());return!1})};return{init:function(b){$.extend(a,b);f=parseInt(a.images.length,
10)-1;d=parseInt(a.currentSelectedImageIndex,10);x();u()},changeOrder:function(b){var c=[],e,g;for(e=0;e<b.length;e++)for(g=0;g<a.images.length;g++)parseInt(b[e].id,10)===a.images[g].id&&(a.images[g].caption=b[e].caption,c.push(a.images[g]),$("#thumbnail-"+e).find("img").attr("src",c[e].thumbnailUrl),$("#thumbnail-"+e).find("img").attr("alt",a.images[g].caption));a.images=c;d=-1;h(0,!1,!1)},setupInitialImagePreload:function(){setTimeout(function(){var b=a.numberOfImagesToPreloadBeforeCurrent+a.numberOfImagesToPreloadAfterCurrent,
d=l(a.currentSelectedImageIndex-a.numberOfImagesToPreloadBeforeCurrent),e=[],g;for(g=0;g<a.images.length;g++)e.push(a.images[g].masterUrl);c=new RIGHTMOVE.UTIL.ImageLoader(e,d,b);c.start()},100)},startSlideshow:t}}()})();
(function(){var p=RIGHTMOVE.namespace("RIGHTMOVE.UTIL"),k=function(f,d,k){this.loadedImages=[];this.failureImages=[];this.queuedImages=[];this.imageUrls=f;this.startIndex=d;this.preloadImage=function(c,a){if(!this.loadedImages[c]){var d=document.createElement("img");d.onerror=RIGHTMOVE.bind(this,function(){this.addFailureImage(d,c);a()});d.onload=a;d.src=this.imageUrls[c];this.loadedImages[c]=d}};this.addFailureImage=function(c,a){this.failureImages[c.src]={index:a}};this.getFailureImageBySrc=function(c){return this.failureImages[c]};
this.preloadNextImageFromQueue=function(){if(0<this.queuedImages.length){var c=this.queuedImages.shift();this.preloadImage(c,RIGHTMOVE.bind(this,this.preloadNextImageFromQueue))}};this.setupQueueWithStartingIndex=function(c){var a=[],d=[],f;for(f=0;f<this.imageUrls.length;f++)this.loadedImages[f]||(f>=c?a.push(f):d.push(f));this.queuedImages=a.concat(d)};this.startPreloading=function(){var c;for(c=0;c<k&&0<this.queuedImages.length;c++)this.preloadNextImageFromQueue()};this.setupQueueWithStartingIndex(this.startIndex)};
k.prototype={updateCurrentIndex:function(f){this.setupQueueWithStartingIndex(f)},start:function(){this.startPreloading()},isImageSrcFailure:function(f){return void 0!==this.getFailureImageBySrc(f)}};p.ImageLoader=k})();